# Generated by Django 4.2.8 on 2024-01-03 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_alter_course_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
